name: Auto Update

on:
  schedule:
    - cron: "0 0 1 * *"  # 每月1号 00:00 UTC
  workflow_dispatch:      # 允许手动触发测试

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update timestamp in subfolder
        run: |
          # 确保在对应的文件夹内更新时间戳
          echo "Last run: $(date)" > koyeb-alive/keepalive.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add koyeb-alive/keepalive.txt
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto update koyeb-alive $(date)"
            git push
          fi
